### ISSUE TITLE
Outdated rootfs

### ISSUE THREAD

**Issue by jaxvanyang** [AlexTalker/archriscv-docker-draft#1]
Hi, it's been a while since your last update. I don't know if you have time to update this repository. If you don't, I would like to help.

I want to write a automatic CI workflow to apply the most recent rootfs, and add some logic to do cleanup. Maybe once a month. This shouldn't be difficult. I can contribute a PR if you like. Or if you are too busy to maintain this repo, I will fork it and publish it to my Docker registry.

**Comment by jaxvanyang** [comment]
OK, 3 days passed. You must be very busy. I'll create a fork first. If still no response in this week. I will push it to my own Docker registry.

**Comment by jaxvanyang** [comment]
I have published it to my own [Docker repository](https://hub.docker.com/repository/docker/jaxvanyang/archriscv). Anyone interested could check it over there.

**Comment by AlexTalker** [comment]
@jaxvanyang Aye, due to a number of factors in live I haven't had time to continue with this "enterprise" RISC-V setup, so much so that the 2nd iteration of StarFive VisionFive came out, so I'm definitely lagging behind. Thanks for taking the interest tho.

**Comment by jaxvanyang** [comment]
Understood, hope you are well.

**Comment by AlexTalker** [comment]
@jaxvanyang Yeah, just busy. I've pushed the CI to build the latest image few days ago. I might look to automate this process(of tracking latest version) when I'll get some time =)

**Comment by jaxvanyang** [comment]
I have done that already, I can create a pr if you like.

**Comment by AlexTalker** [comment]
@jaxvanyang Feel free, I've personally thought about using something like https://beautiful-soup-4.readthedocs.io/en/latest/ to nicely parse NGNIX `autoindex` output and put it into GitHub Action that runs periodically(once a week say would suffice for most) that triggers the main action with new `env` but you do you =)

**Comment by jaxvanyang** [comment]
I use a silly curl approach, but it works fine. #3

**Comment by AlexTalker** [comment]
@jaxvanyang that PR seems to have way too many changes methinks, I see where you're going with this tho. I think that docker-related things, if needed at all, should be in a separate `Makefile` file that can be `include`d. Also, using `make` rule to compute the version is an overkill, in my opinion it is preferable to store such hacks in a separate script.

As I understand, you are trying to build & publish the image locally and/or on different CI than GitHub Actions but at this moment I doubt there's a need for that. I planned to support `GitLab` in the future also but oh well =)

**Comment by AlexTalker** [comment]
Thanks for taking a look tho

**Comment by jaxvanyang** [comment]
Just a hint, you can pick what you like. Maybe grab that curl thing to a shell script or something. I know my method is somewhat dirty. So if you have better idea, just do it.

**Comment by jaxvanyang** [comment]
@AlexTalker FYI, another person is maintaining an up-to-date Docker image.
- https://archriscv.felixc.at
- https://hub.docker.com/r/riscfive/archlinux

**Comment by AlexTalker** [comment]
@jaxvanyang nice that the ppl finally caught on =)

Anyway, I've added automated weekly update of the images, including bumping to new release version.

It has a room to be more polished but it works for now.

I'll see what comes out of it since I initially intended this image as an environment to package building but due to certain fundamental flaw regarding `exec*()` exit code in `QEMU userspace`, my thoughts now more in the direction of full-on emulation since I lack powerful RISC-V hardware at the moment.
